/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/appwavelets/kube-git/pkg/apis/githook/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGitHooks implements GitHookInterface
type FakeGitHooks struct {
	Fake *FakeKubegitV1alpha1
	ns   string
}

var githooksResource = schema.GroupVersionResource{Group: "kubegit.appwavelets.com", Version: "v1alpha1", Resource: "githooks"}

var githooksKind = schema.GroupVersionKind{Group: "kubegit.appwavelets.com", Version: "v1alpha1", Kind: "GitHook"}

// Get takes name of the gitHook, and returns the corresponding gitHook object, and an error if there is any.
func (c *FakeGitHooks) Get(name string, options v1.GetOptions) (result *v1alpha1.GitHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(githooksResource, c.ns, name), &v1alpha1.GitHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitHook), err
}

// List takes label and field selectors, and returns the list of GitHooks that match those selectors.
func (c *FakeGitHooks) List(opts v1.ListOptions) (result *v1alpha1.GitHookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(githooksResource, githooksKind, c.ns, opts), &v1alpha1.GitHookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GitHookList{ListMeta: obj.(*v1alpha1.GitHookList).ListMeta}
	for _, item := range obj.(*v1alpha1.GitHookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gitHooks.
func (c *FakeGitHooks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(githooksResource, c.ns, opts))

}

// Create takes the representation of a gitHook and creates it.  Returns the server's representation of the gitHook, and an error, if there is any.
func (c *FakeGitHooks) Create(gitHook *v1alpha1.GitHook) (result *v1alpha1.GitHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(githooksResource, c.ns, gitHook), &v1alpha1.GitHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitHook), err
}

// Update takes the representation of a gitHook and updates it. Returns the server's representation of the gitHook, and an error, if there is any.
func (c *FakeGitHooks) Update(gitHook *v1alpha1.GitHook) (result *v1alpha1.GitHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(githooksResource, c.ns, gitHook), &v1alpha1.GitHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitHook), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGitHooks) UpdateStatus(gitHook *v1alpha1.GitHook) (*v1alpha1.GitHook, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(githooksResource, "status", c.ns, gitHook), &v1alpha1.GitHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitHook), err
}

// Delete takes name of the gitHook and deletes it. Returns an error if one occurs.
func (c *FakeGitHooks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(githooksResource, c.ns, name), &v1alpha1.GitHook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitHooks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(githooksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GitHookList{})
	return err
}

// Patch applies the patch and returns the patched gitHook.
func (c *FakeGitHooks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(githooksResource, c.ns, name, pt, data, subresources...), &v1alpha1.GitHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitHook), err
}
